name: daily notebook action
on:
  push:
    branches:
      - main
#  schedule:
#    - cron: '0 0 * * *'
jobs:
  notebook-run:
    runs-on: ubuntu-latest 
    env: 
      CI_COMMIT_MESSAGE: notebook run
    permissions:
      contents: write  
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: install requirements
      run: pip3 install -r requirements.txt
    - name: run script
      run: ./run.sh
    - name: directory contents
      run: ls -al
    - name: push repo
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add csv/
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
        
